name: pinch_zoom
description: A widget based on Flutter's new Interactive Viewer that makes picture pinch zoom, and return to its initial size and position when released.
version: 0.1.0
homepage: https://github.com/tkortekaas/pinch_zoom

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

repository: https://github.com/tkortekaas/pinch_zoom

flutter:
